//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_roomtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_roomtype()
        {
            this.tbl_room = new HashSet<tbl_room>();
        }
    
        public int roomtype_id { get; set; }
        public string room_type { get; set; }
        public Nullable<int> room_price { get; set; }
        public string room_photo { get; set; }
        public string room_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_room> tbl_room { get; set; }
    }
}
