//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_customer()
        {
            this.tbl_reservation = new HashSet<tbl_reservation>();
        }
    
        public int cust_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string city { get; set; }
        public Nullable<int> pincode { get; set; }
        public Nullable<long> contact_no { get; set; }
        public string email { get; set; }
        public Nullable<long> aadharcard_no { get; set; }
        public string password { get; set; }
        public string cpassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reservation> tbl_reservation { get; set; }
        public virtual tbl_payment tbl_payment { get; set; }
        public virtual tbl_feedback tbl_feedback { get; set; }
    }
}
