//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int payment_id { get; set; }
        public string name { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> res_id { get; set; }
        public Nullable<int> cust_id { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_reservation tbl_reservation { get; set; }
    }
}
