//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelreservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reservation
    {
        public int res_id { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<int> no_of_adult { get; set; }
        public Nullable<int> total_amount { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_room tbl_room { get; set; }
        public virtual tbl_payment tbl_payment { get; set; }
    }
}
